-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 01, 2021 at 05:33 AM
-- Server version: 10.4.14-MariaDB
-- PHP Version: 7.4.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `weatherapps`
--

-- --------------------------------------------------------

--
-- Table structure for table `weather`
--

CREATE TABLE `weather` (
  `id` int(11) NOT NULL,
  `city` varchar(50) NOT NULL,
  `country` varchar(50) NOT NULL,
  `data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`data`)),
  `expire` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `weather`
--

INSERT INTO `weather` (`id`, `city`, `country`, `data`, `expire`) VALUES
(1, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:45\",\"localtime_epoch\":1616323500,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:45 AM\",\"temperature\":31,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":13,\"wind_degree\":240,\"wind_dir\":\"WSW\",\"pressure\":1008,\"precip\":0,\"humidity\":63,\"cloudcover\":50,\"feelslike\":36,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 1),
(2, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:48\",\"localtime_epoch\":1616323680,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:48 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 20),
(3, 'london', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:52\",\"localtime_epoch\":1616323920,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:52 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 60),
(4, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:48\",\"localtime_epoch\":1616323680,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:48 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 2),
(5, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:56\",\"localtime_epoch\":1616324160,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:56 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 1616299576),
(6, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:56\",\"localtime_epoch\":1616324160,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:56 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 1616299588),
(7, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:56\",\"localtime_epoch\":1616324160,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:56 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 1616299651),
(8, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:56\",\"localtime_epoch\":1616324160,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:56 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 1616299822),
(9, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:56\",\"localtime_epoch\":1616324160,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:56 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 1616299271),
(10, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:56\",\"localtime_epoch\":1616324160,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:56 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 1616299517),
(11, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:56\",\"localtime_epoch\":1616324160,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:56 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 1616299523),
(12, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-21 10:56\",\"localtime_epoch\":1616324160,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:56 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":11,\"wind_degree\":300,\"wind_dir\":\"WNW\",\"pressure\":1007,\"precip\":0,\"humidity\":52,\"cloudcover\":25,\"feelslike\":38,\"uv_index\":7,\"visibility\":6,\"is_day\":\"yes\"}}', 1616299530),
(13, 'london', 'united kingdom', '{\"request\":{\"type\":\"City\",\"query\":\"London, United Kingdom\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"London\",\"country\":\"United Kingdom\",\"region\":\"City of London, Greater London\",\"lat\":\"51.517\",\"lon\":\"-0.106\",\"timezone_id\":\"Europe/London\",\"localtime\":\"2021-03-21 04:05\",\"localtime_epoch\":1616299500,\"utc_offset\":\"0.0\"},\"current\":{\"observation_time\":\"04:05 AM\",\"temperature\":8,\"weather_code\":122,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png\"],\"weather_descriptions\":[\"Overcast\"],\"wind_speed\":9,\"wind_degree\":330,\"wind_dir\":\"NNW\",\"pressure\":1028,\"precip\":0,\"humidity\":76,\"cloudcover\":100,\"feelslike\":6,\"uv_index\":1,\"visibility\":10,\"is_day\":\"no\"}}', 1616299547),
(14, 'london', 'united kingdom', '{\"request\":{\"type\":\"City\",\"query\":\"London, United Kingdom\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"London\",\"country\":\"United Kingdom\",\"region\":\"City of London, Greater London\",\"lat\":\"51.517\",\"lon\":\"-0.106\",\"timezone_id\":\"Europe/London\",\"localtime\":\"2021-03-21 04:05\",\"localtime_epoch\":1616299500,\"utc_offset\":\"0.0\"},\"current\":{\"observation_time\":\"04:05 AM\",\"temperature\":8,\"weather_code\":122,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png\"],\"weather_descriptions\":[\"Overcast\"],\"wind_speed\":9,\"wind_degree\":330,\"wind_dir\":\"NNW\",\"pressure\":1028,\"precip\":0,\"humidity\":76,\"cloudcover\":100,\"feelslike\":6,\"uv_index\":1,\"visibility\":10,\"is_day\":\"no\"}}', 1616299553),
(15, 'woodside', 'australia', '{\"request\":{\"type\":\"City\",\"query\":\"Woodside, Australia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Woodside\",\"country\":\"Australia\",\"region\":\"South Australia\",\"lat\":\"-34.950\",\"lon\":\"138.867\",\"timezone_id\":\"Australia/Adelaide\",\"localtime\":\"2021-03-21 14:36\",\"localtime_epoch\":1616337360,\"utc_offset\":\"10.50\"},\"current\":{\"observation_time\":\"04:06 AM\",\"temperature\":27,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":12,\"wind_degree\":90,\"wind_dir\":\"E\",\"pressure\":1018,\"precip\":0,\"humidity\":37,\"cloudcover\":14,\"feelslike\":27,\"uv_index\":7,\"visibility\":10,\"is_day\":\"yes\"}}', 1616299581),
(16, 'woodside', 'australia', '{\"request\":{\"type\":\"City\",\"query\":\"Woodside, Australia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Woodside\",\"country\":\"Australia\",\"region\":\"South Australia\",\"lat\":\"-34.950\",\"lon\":\"138.867\",\"timezone_id\":\"Australia/Adelaide\",\"localtime\":\"2021-03-21 14:36\",\"localtime_epoch\":1616337360,\"utc_offset\":\"10.50\"},\"current\":{\"observation_time\":\"04:06 AM\",\"temperature\":27,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":12,\"wind_degree\":90,\"wind_dir\":\"E\",\"pressure\":1018,\"precip\":0,\"humidity\":37,\"cloudcover\":14,\"feelslike\":27,\"uv_index\":7,\"visibility\":10,\"is_day\":\"yes\"}}', 1616299596),
(17, 'woodside', 'united kingdom', '{\"request\":{\"type\":\"City\",\"query\":\"Woodside, United Kingdom\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Woodside\",\"country\":\"United Kingdom\",\"region\":\"Aberdeen City\",\"lat\":\"57.167\",\"lon\":\"-2.142\",\"timezone_id\":\"Europe/London\",\"localtime\":\"2021-03-21 04:18\",\"localtime_epoch\":1616300280,\"utc_offset\":\"0.0\"},\"current\":{\"observation_time\":\"04:18 AM\",\"temperature\":6,\"weather_code\":122,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png\"],\"weather_descriptions\":[\"Overcast\"],\"wind_speed\":19,\"wind_degree\":310,\"wind_dir\":\"NW\",\"pressure\":1028,\"precip\":0,\"humidity\":70,\"cloudcover\":100,\"feelslike\":2,\"uv_index\":1,\"visibility\":10,\"is_day\":\"no\"}}', 1616300331),
(18, 'woodside', 'united kingdom', '{\"request\":{\"type\":\"City\",\"query\":\"Woodside, United Kingdom\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Woodside\",\"country\":\"United Kingdom\",\"region\":\"Aberdeen City\",\"lat\":\"57.167\",\"lon\":\"-2.142\",\"timezone_id\":\"Europe/London\",\"localtime\":\"2021-03-21 04:18\",\"localtime_epoch\":1616300280,\"utc_offset\":\"0.0\"},\"current\":{\"observation_time\":\"04:18 AM\",\"temperature\":6,\"weather_code\":122,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png\"],\"weather_descriptions\":[\"Overcast\"],\"wind_speed\":19,\"wind_degree\":310,\"wind_dir\":\"NW\",\"pressure\":1028,\"precip\":0,\"humidity\":70,\"cloudcover\":100,\"feelslike\":2,\"uv_index\":1,\"visibility\":10,\"is_day\":\"no\"}}', 1616300389),
(19, 'woodside', 'united kingdom', '{\"request\":{\"type\":\"City\",\"query\":\"Woodside, United Kingdom\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Woodside\",\"country\":\"United Kingdom\",\"region\":\"Aberdeen City\",\"lat\":\"57.167\",\"lon\":\"-2.142\",\"timezone_id\":\"Europe/London\",\"localtime\":\"2021-03-21 04:18\",\"localtime_epoch\":1616300280,\"utc_offset\":\"0.0\"},\"current\":{\"observation_time\":\"04:18 AM\",\"temperature\":6,\"weather_code\":122,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png\"],\"weather_descriptions\":[\"Overcast\"],\"wind_speed\":19,\"wind_degree\":310,\"wind_dir\":\"NW\",\"pressure\":1028,\"precip\":0,\"humidity\":70,\"cloudcover\":100,\"feelslike\":2,\"uv_index\":1,\"visibility\":10,\"is_day\":\"no\"}}', 1616300402),
(20, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-28 10:09\",\"localtime_epoch\":1616926140,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"03:09 AM\",\"temperature\":30,\"weather_code\":143,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0006_mist.png\"],\"weather_descriptions\":[\"Haze\"],\"wind_speed\":6,\"wind_degree\":100,\"wind_dir\":\"E\",\"pressure\":1008,\"precip\":0.1,\"humidity\":70,\"cloudcover\":25,\"feelslike\":35,\"uv_index\":6,\"visibility\":4,\"is_day\":\"yes\"}}', 1616900938),
(21, 'ip', 'romania', '{\"request\":{\"type\":\"City\",\"query\":\"Ip, Romania\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Ip\",\"country\":\"Romania\",\"region\":\"Bihor\",\"lat\":\"47.233\",\"lon\":\"22.650\",\"timezone_id\":\"Europe/Bucharest\",\"localtime\":\"2021-03-28 06:52\",\"localtime_epoch\":1616914320,\"utc_offset\":\"3.0\"},\"current\":{\"observation_time\":\"03:52 AM\",\"temperature\":5,\"weather_code\":296,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png\"],\"weather_descriptions\":[\"Light Rain\"],\"wind_speed\":13,\"wind_degree\":320,\"wind_dir\":\"NW\",\"pressure\":1024,\"precip\":0.2,\"humidity\":87,\"cloudcover\":75,\"feelslike\":4,\"uv_index\":1,\"visibility\":9,\"is_day\":\"no\"}}', 1616903547),
(22, 'ip', 'romania', '{\"request\":{\"type\":\"City\",\"query\":\"Ip, Romania\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Ip\",\"country\":\"Romania\",\"region\":\"Bihor\",\"lat\":\"47.233\",\"lon\":\"22.650\",\"timezone_id\":\"Europe/Bucharest\",\"localtime\":\"2021-03-28 06:56\",\"localtime_epoch\":1616914560,\"utc_offset\":\"3.0\"},\"current\":{\"observation_time\":\"03:56 AM\",\"temperature\":5,\"weather_code\":296,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png\"],\"weather_descriptions\":[\"Light Rain\"],\"wind_speed\":13,\"wind_degree\":320,\"wind_dir\":\"NW\",\"pressure\":1024,\"precip\":0.2,\"humidity\":87,\"cloudcover\":75,\"feelslike\":4,\"uv_index\":1,\"visibility\":9,\"is_day\":\"no\"}}', 1616903811),
(23, 'ip', 'romania', '{\"request\":{\"type\":\"City\",\"query\":\"Ip, Romania\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Ip\",\"country\":\"Romania\",\"region\":\"Bihor\",\"lat\":\"47.233\",\"lon\":\"22.650\",\"timezone_id\":\"Europe/Bucharest\",\"localtime\":\"2021-03-28 07:06\",\"localtime_epoch\":1616915160,\"utc_offset\":\"3.0\"},\"current\":{\"observation_time\":\"04:06 AM\",\"temperature\":5,\"weather_code\":296,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png\"],\"weather_descriptions\":[\"Light Rain\"],\"wind_speed\":13,\"wind_degree\":320,\"wind_dir\":\"NW\",\"pressure\":1024,\"precip\":0.1,\"humidity\":87,\"cloudcover\":75,\"feelslike\":4,\"uv_index\":1,\"visibility\":9,\"is_day\":\"no\"}}', 1616904383),
(24, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-28 11:10\",\"localtime_epoch\":1616929800,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"04:10 AM\",\"temperature\":31,\"weather_code\":143,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0006_mist.png\"],\"weather_descriptions\":[\"Haze\"],\"wind_speed\":9,\"wind_degree\":120,\"wind_dir\":\"ESE\",\"pressure\":1008,\"precip\":0.1,\"humidity\":66,\"cloudcover\":25,\"feelslike\":36,\"uv_index\":8,\"visibility\":5,\"is_day\":\"yes\"}}', 1616904603),
(25, 'jakarta', 'indonesia', '{\"request\":{\"type\":\"City\",\"query\":\"Jakarta, Indonesia\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Jakarta\",\"country\":\"Indonesia\",\"region\":\"Jakarta Raya\",\"lat\":\"-6.215\",\"lon\":\"106.845\",\"timezone_id\":\"Asia/Jakarta\",\"localtime\":\"2021-03-28 11:20\",\"localtime_epoch\":1616930400,\"utc_offset\":\"7.0\"},\"current\":{\"observation_time\":\"04:20 AM\",\"temperature\":32,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":9,\"wind_degree\":90,\"wind_dir\":\"E\",\"pressure\":1008,\"precip\":0.1,\"humidity\":63,\"cloudcover\":25,\"feelslike\":39,\"uv_index\":8,\"visibility\":6,\"is_day\":\"yes\"}}', 1616905244),
(26, 'poonarunna station', 'australia', '{\"request\":{\"type\":\"LatLon\",\"query\":\"Lat -26.46 and Lon 137.07\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"Poonarunna Station\",\"country\":\"Australia\",\"region\":\"South Australia\",\"lat\":\"-27.833\",\"lon\":\"137.550\",\"timezone_id\":\"Australia/Adelaide\",\"localtime\":\"2021-03-28 14:51\",\"localtime_epoch\":1616943060,\"utc_offset\":\"10.50\"},\"current\":{\"observation_time\":\"04:21 AM\",\"temperature\":28,\"weather_code\":116,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png\"],\"weather_descriptions\":[\"Partly cloudy\"],\"wind_speed\":21,\"wind_degree\":145,\"wind_dir\":\"SE\",\"pressure\":1016,\"precip\":0,\"humidity\":38,\"cloudcover\":45,\"feelslike\":27,\"uv_index\":7,\"visibility\":10,\"is_day\":\"yes\"}}', 1616905303),
(27, 'london', 'united kingdom', '{\"request\":{\"type\":\"City\",\"query\":\"London, United Kingdom\",\"language\":\"en\",\"unit\":\"m\"},\"location\":{\"name\":\"London\",\"country\":\"United Kingdom\",\"region\":\"City of London, Greater London\",\"lat\":\"51.517\",\"lon\":\"-0.106\",\"timezone_id\":\"Europe/London\",\"localtime\":\"2021-03-28 05:22\",\"localtime_epoch\":1616908920,\"utc_offset\":\"1.0\"},\"current\":{\"observation_time\":\"04:22 AM\",\"temperature\":10,\"weather_code\":113,\"weather_icons\":[\"https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0008_clear_sky_night.png\"],\"weather_descriptions\":[\"Clear\"],\"wind_speed\":20,\"wind_degree\":230,\"wind_dir\":\"SW\",\"pressure\":1021,\"precip\":0,\"humidity\":66,\"cloudcover\":0,\"feelslike\":7,\"uv_index\":1,\"visibility\":10,\"is_day\":\"no\"}}', 1616905335);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `weather`
--
ALTER TABLE `weather`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `weather`
--
ALTER TABLE `weather`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=28;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
